/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["v1_auth_login_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/PATCH the logged-in user's own profile + basic info. */
        get: operations["v1_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description GET/PATCH the logged-in user's own profile + basic info. */
        patch: operations["v1_auth_me_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/generate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST a start point and target distance, get back ranked loop options.
         *
         *     Routes are ephemeral — generated on demand, not persisted. Saving
         *     favourites comes later, once route quality is tuned.
         */
        post: operations["v1_routes_generate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Workout history and GPS ingest.
         *
         *     Scoped to the requesting user for now. When the social graph lands,
         *     this widens to include followed athletes' public workouts — but the
         *     default stays restrictive rather than permissive.
         */
        get: operations["v1_workouts_list"];
        put?: never;
        /**
         * @description Workout history and GPS ingest.
         *
         *     Scoped to the requesting user for now. When the social graph lands,
         *     this widens to include followed athletes' public workouts — but the
         *     default stays restrictive rather than permissive.
         */
        post: operations["v1_workouts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Workout history and GPS ingest.
         *
         *     Scoped to the requesting user for now. When the social graph lands,
         *     this widens to include followed athletes' public workouts — but the
         *     default stays restrictive rather than permissive.
         */
        get: operations["v1_workouts_retrieve"];
        /**
         * @description Workout history and GPS ingest.
         *
         *     Scoped to the requesting user for now. When the social graph lands,
         *     this widens to include followed athletes' public workouts — but the
         *     default stays restrictive rather than permissive.
         */
        put: operations["v1_workouts_update"];
        post?: never;
        /**
         * @description Workout history and GPS ingest.
         *
         *     Scoped to the requesting user for now. When the social graph lands,
         *     this widens to include followed athletes' public workouts — but the
         *     default stays restrictive rather than permissive.
         */
        delete: operations["v1_workouts_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Workout history and GPS ingest.
         *
         *     Scoped to the requesting user for now. When the social graph lands,
         *     this widens to include followed athletes' public workouts — but the
         *     default stays restrictive rather than permissive.
         */
        patch: operations["v1_workouts_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `run` - Run
         *     * `walk` - Walk
         *     * `hike` - Hike
         *     * `ride` - Ride
         * @enum {string}
         */
        ActivityTypeEnum: "run" | "walk" | "hike" | "ride";
        PaginatedWorkoutListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["WorkoutList"][];
        };
        /** @description Full view, including the path geometry as GeoJSON. */
        PatchedWorkoutDetail: {
            readonly id?: number;
            activity_type?: components["schemas"]["ActivityTypeEnum"];
            source?: components["schemas"]["SourceEnum"];
            privacy?: components["schemas"]["PrivacyEnum"];
            title?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            ended_at?: string;
            /** Format: double */
            distance_m?: number;
            /** Format: double */
            readonly distance_mi?: number;
            duration_s?: number;
            moving_time_s?: number;
            /** Format: double */
            readonly pace_s_per_mi?: number;
            /** Format: double */
            elevation_gain_m?: number;
            average_heart_rate?: number | null;
            max_heart_rate?: number | null;
            notes?: string;
            /** Format: double */
            elevation_loss_m?: number;
            calories?: number | null;
            splits?: unknown;
            telemetry?: unknown;
            readonly geometry?: string;
        };
        /**
         * @description * `public` - Public
         *     * `followers` - Followers only
         *     * `private` - Private
         * @enum {string}
         */
        PrivacyEnum: "public" | "followers" | "private";
        Register: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            password: string;
            password_confirm: string;
        };
        /**
         * @description * `phone` - Phone GPS
         *     * `watch` - Watch
         *     * `manual` - Manual entry
         *     * `import` - Imported file
         * @enum {string}
         */
        SourceEnum: "phone" | "watch" | "manual" | "import";
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TrackPoint: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /** Format: date-time */
            timestamp: string;
            /** Format: double */
            elevation?: number | null;
            heart_rate?: number | null;
            cadence?: number | null;
        };
        /**
         * @description Accepts a raw GPS track. Distance, duration, splits and elevation
         *     are all computed server-side — never trust client-reported totals,
         *     since they vary by device and can be trivially faked on a
         *     leaderboard.
         */
        WorkoutCreate: {
            readonly id: number;
            activity_type?: components["schemas"]["ActivityTypeEnum"];
            source?: components["schemas"]["SourceEnum"];
            privacy?: components["schemas"]["PrivacyEnum"];
            title?: string;
            notes?: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string;
            points?: components["schemas"]["TrackPoint"][];
        };
        /** @description Full view, including the path geometry as GeoJSON. */
        WorkoutDetail: {
            readonly id: number;
            activity_type?: components["schemas"]["ActivityTypeEnum"];
            source?: components["schemas"]["SourceEnum"];
            privacy?: components["schemas"]["PrivacyEnum"];
            title?: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string;
            /** Format: double */
            distance_m?: number;
            /** Format: double */
            readonly distance_mi: number;
            duration_s?: number;
            moving_time_s?: number;
            /** Format: double */
            readonly pace_s_per_mi: number;
            /** Format: double */
            elevation_gain_m?: number;
            average_heart_rate?: number | null;
            max_heart_rate?: number | null;
            notes?: string;
            /** Format: double */
            elevation_loss_m?: number;
            calories?: number | null;
            splits?: unknown;
            telemetry?: unknown;
            readonly geometry: string;
        };
        /**
         * @description Summary view. Deliberately excludes geometry and telemetry —
         *     a history screen shouldn't transfer megabytes of coordinates.
         */
        WorkoutList: {
            readonly id: number;
            activity_type?: components["schemas"]["ActivityTypeEnum"];
            source?: components["schemas"]["SourceEnum"];
            privacy?: components["schemas"]["PrivacyEnum"];
            title?: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            ended_at: string;
            /** Format: double */
            distance_m?: number;
            /** Format: double */
            readonly distance_mi: number;
            duration_s?: number;
            moving_time_s?: number;
            /** Format: double */
            readonly pace_s_per_mi: number;
            /** Format: double */
            elevation_gain_m?: number;
            average_heart_rate?: number | null;
            max_heart_rate?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    v1_auth_login_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    v1_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    v1_routes_generate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_workouts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkoutListList"];
                };
            };
        };
    };
    v1_workouts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkoutCreate"];
                "multipart/form-data": components["schemas"]["WorkoutCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutCreate"];
                };
            };
        };
    };
    v1_workouts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutDetail"];
                };
            };
        };
    };
    v1_workouts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkoutDetail"];
                "multipart/form-data": components["schemas"]["WorkoutDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutDetail"];
                };
            };
        };
    };
    v1_workouts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_workouts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWorkoutDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWorkoutDetail"];
                "multipart/form-data": components["schemas"]["PatchedWorkoutDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutDetail"];
                };
            };
        };
    };
}
