# Generated by Django 5.1.15 on 2026-08-06 21:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('run', 'Run'), ('walk', 'Walk'), ('hike', 'Hike'), ('ride', 'Ride')], default='run', max_length=10)),
                ('source', models.CharField(choices=[('phone', 'Phone GPS'), ('watch', 'Watch'), ('manual', 'Manual entry'), ('import', 'Imported file')], default='phone', max_length=10)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers only'), ('private', 'Private')], default='followers', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('path', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('distance_m', models.FloatField(default=0.0)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('moving_time_s', models.PositiveIntegerField(default=0)),
                ('elevation_gain_m', models.FloatField(default=0.0)),
                ('elevation_loss_m', models.FloatField(default=0.0)),
                ('average_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('telemetry', models.JSONField(blank=True, default=list)),
                ('splits', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='workouts_wo_user_id_9aedf7_idx'), models.Index(fields=['activity_type'], name='workouts_wo_activit_1de09e_idx')],
            },
        ),
    ]
